version: '3.8'

services:
  # Single PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: attendance_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Services
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=attendance_app
      - JWT_SECRET=default-secret
      - JWT_EXPIRES_IN=7d
      - PORT=3001
    depends_on:
      - postgres

  employee-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=attendance_app
      - PORT=3002
    depends_on:
      - postgres

  attendance-service:
    build:
      context: ./services/attendance-service
      dockerfile: Dockerfile
    ports:
      - '3003:3003'
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=attendance_app
      - PORT=3003
    depends_on:
      - postgres

  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - AUTH_SERVICE_URL=http://auth-service:3001
      - EMPLOYEE_SERVICE_URL=http://employee-service:3002
      - ATTENDANCE_SERVICE_URL=http://attendance-service:3003
    depends_on:
      - auth-service
      - employee-service
      - attendance-service

  # Frontend Applications
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3004:80'
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    depends_on:
      - api-gateway

  admin-frontend:
    build:
      context: ./admin-frontend
      dockerfile: Dockerfile
    ports:
      - '3005:80'
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    depends_on:
      - api-gateway

volumes:
  postgres_data:
